sudo: required
services:
    - docker

before_install:
    - docker build -t antonizhu/dbsinvest .

script:
    - docker run antonizhu/dbsinvest python manage.py test

#after_success:
#    - docker build -t antonizhu/dbsinvest .