# Generated by Django 2.2.5 on 2019-10-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etf',
            name='etfName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
