# Generated by Django 2.2.5 on 2019-10-26 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20191026_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etf',
            old_name='etfName',
            new_name='name',
        ),
    ]
